### PR TITLE
Replaced all init() methods with one versatile and intuitive one

### PR DESCRIPTION
**Pull request by Evertt**
This does everything I mentioned in #8. I actually added two more init() methods initially which utilised `@autoclosure`, but I removed them, because I thought they might be confusing.

Now it's very consistent, attributes go between parentheses `()` and children go between curly brackets `{}`. And attributes always go before children, just like in HTML. And both arguments have a default value so you don't need to make the `convenience init()` methods.

## edit

I just assumed I should merge this to the 2.0 branch. Is that correct? Otherwise I'll open a new PR for the master branch.

### CODE REVIEW

**Comment by sahandnayebaziz** [comment]
@Evertt the 2.0 branch is fine! I'm merging approved changes into master and into the 2.0.0 Beta releases, but I made a 2.0 branch to write new tests and updates to the readme without having to make them to `master` where you can see them on the main page.

**Comment by sahandnayebaziz** [comment]
hey @Evertt, I have been reviewing this change and I think it looks good :) Can you pull from the origin 2.0 branch and update the two tests `testCanRenderAttributeOnNestedTag` and `testCanRenderTagsWithFormatting` without the `attributes` parameter? Those are failing right now with `attributes:` still in the initializer

**Comment by Evertt** [comment]
This might sounds a bit stupid, but how do I actually run those tests? Do I use the swift command line interface in some way for that? Or do I need to import the code in Xcode?

**Comment by sahandnayebaziz** [comment]
@Evertt not stupid at all! I hope you did it with `swift test`, that's the easiest way :)

**Pull request merged**
